/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as TherapistRouteImport } from './routes/therapist'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardJournalRouteImport } from './routes/dashboard.journal'
import { Route as DashboardProgressRouteImport } from './routes/dashboard.progress'
import { Route as TherapistIndexRouteImport } from './routes/therapist.index'
import { Route as TherapistPatientsRouteImport } from './routes/therapist.patients'
import { Route as TherapistScheduleRouteImport } from './routes/therapist.schedule'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TherapistRoute = TherapistRouteImport.update({
  id: '/therapist',
  path: '/therapist',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJournalRoute = DashboardJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProgressRoute = DashboardProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => DashboardRoute,
} as any)
const TherapistIndexRoute = TherapistIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TherapistRoute,
} as any)
const TherapistPatientsRoute = TherapistPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => TherapistRoute,
} as any)
const TherapistScheduleRoute = TherapistScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => TherapistRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/therapist': typeof TherapistRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/journal': typeof DashboardJournalRoute
  '/dashboard/progress': typeof DashboardProgressRoute
  '/therapist/patients': typeof TherapistPatientsRoute
  '/therapist/schedule': typeof TherapistScheduleRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/therapist/': typeof TherapistIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/journal': typeof DashboardJournalRoute
  '/dashboard/progress': typeof DashboardProgressRoute
  '/therapist/patients': typeof TherapistPatientsRoute
  '/therapist/schedule': typeof TherapistScheduleRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/therapist': typeof TherapistIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/therapist': typeof TherapistRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/journal': typeof DashboardJournalRoute
  '/dashboard/progress': typeof DashboardProgressRoute
  '/therapist/patients': typeof TherapistPatientsRoute
  '/therapist/schedule': typeof TherapistScheduleRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/therapist/': typeof TherapistIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/therapist'
    | '/admin/users'
    | '/dashboard/journal'
    | '/dashboard/progress'
    | '/therapist/patients'
    | '/therapist/schedule'
    | '/admin/'
    | '/dashboard/'
    | '/therapist/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/users'
    | '/dashboard/journal'
    | '/dashboard/progress'
    | '/therapist/patients'
    | '/therapist/schedule'
    | '/admin'
    | '/dashboard'
    | '/therapist'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/therapist'
    | '/admin/users'
    | '/dashboard/journal'
    | '/dashboard/progress'
    | '/therapist/patients'
    | '/therapist/schedule'
    | '/admin/'
    | '/dashboard/'
    | '/therapist/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  TherapistRoute: typeof TherapistRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/therapist': {
      id: '/therapist'
      path: '/therapist'
      fullPath: '/therapist'
      preLoaderRoute: typeof TherapistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/journal': {
      id: '/dashboard/journal'
      path: '/journal'
      fullPath: '/dashboard/journal'
      preLoaderRoute: typeof DashboardJournalRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/progress': {
      id: '/dashboard/progress'
      path: '/progress'
      fullPath: '/dashboard/progress'
      preLoaderRoute: typeof DashboardProgressRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/therapist/': {
      id: '/therapist/'
      path: '/'
      fullPath: '/therapist/'
      preLoaderRoute: typeof TherapistIndexRouteImport
      parentRoute: typeof TherapistRoute
    }
    '/therapist/patients': {
      id: '/therapist/patients'
      path: '/patients'
      fullPath: '/therapist/patients'
      preLoaderRoute: typeof TherapistPatientsRouteImport
      parentRoute: typeof TherapistRoute
    }
    '/therapist/schedule': {
      id: '/therapist/schedule'
      path: '/schedule'
      fullPath: '/therapist/schedule'
      preLoaderRoute: typeof TherapistScheduleRouteImport
      parentRoute: typeof TherapistRoute
    }
  }
}

interface AdminRouteChildren {
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardJournalRoute: typeof DashboardJournalRoute
  DashboardProgressRoute: typeof DashboardProgressRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardJournalRoute: DashboardJournalRoute,
  DashboardProgressRoute: DashboardProgressRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface TherapistRouteChildren {
  TherapistPatientsRoute: typeof TherapistPatientsRoute
  TherapistScheduleRoute: typeof TherapistScheduleRoute
  TherapistIndexRoute: typeof TherapistIndexRoute
}

const TherapistRouteChildren: TherapistRouteChildren = {
  TherapistPatientsRoute: TherapistPatientsRoute,
  TherapistScheduleRoute: TherapistScheduleRoute,
  TherapistIndexRoute: TherapistIndexRoute,
}

const TherapistRouteWithChildren = TherapistRoute._addFileChildren(
  TherapistRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  TherapistRoute: TherapistRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
